Rspec Pull Request
Usagib/gitflowenumerableruby pull request #3
Opened 2020-01-03 00:37 UTC by Usagib

Pull request open for TDD project

2020-01-03 00:59 UTC, Usagib commented
Hello Team!
We made the tests on my enumerable project repo
Sending to code review
Happy Coding! and Happy new Year!

2020-01-03 03:20 UTC, whiz25 requested changes
## Good job :+1: 
You have done well in this project. All your methods pass the tests. But we need to fix a few minor things before we can merge this PR.
Check my comments.

### Martin Afani

2020-01-03 03:23 UTC, whiz25 commented on spec/enumerable_spec.rb
> +  testclass = Class.new
- [ ] it's recommended to declare the variables like;
`let(:test){[2,3,4,5,6,7]},
  let(:testeven){[2,4,6,8,10]},
  let(:testodd){[1,3,5,7,9]},
  let(:hash){{"one" => 1, "two" => 2, "three" => 3}},
  let(:testclass){Class.new}`

2020-01-03 03:25 UTC, whiz25 commented on README.md
>  ### This scripts rebuilds ruby Enumerable methods:
- [ ] The project should have a descriptive README.md ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

2020-01-07 15:37 UTC, Usagib commented
Hello team!, done with the corrections
happy coding

2020-01-07 16:22 UTC, stratospherique approved these changes
### Great Job applying the suggested changes :clap: :clap: The project is approved :heavy_check_mark: You may merge :+1: :+1: :+1: 

Keep up the good work :muscle: 
**_Ahmed Mahfoudh_**

2020-01-08 14:36 UTC, merged